# Generated by Django 4.0.2 on 2022-10-22 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=300, verbose_name='Item code')),
                ('name', models.CharField(max_length=300, verbose_name='Item name')),
                ('description', models.CharField(max_length=300, verbose_name='Item description')),
                ('type', models.CharField(max_length=300, verbose_name='Item type')),
                ('unit_id', models.CharField(max_length=300, verbose_name='Unit ID')),
                ('unit_name', models.CharField(max_length=300, verbose_name='Unit Name')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Warehouse name')),
                ('location', models.CharField(max_length=300, verbose_name='Warehouse Location')),
                ('capacity', models.CharField(blank=True, max_length=300, null=True, verbose_name='Capacity')),
                ('mobile', models.CharField(max_length=300, verbose_name='Mobile')),
                ('email', models.CharField(max_length=300, verbose_name='Email')),
                ('active', models.BooleanField(default=True)),
                ('zip', models.CharField(blank=True, max_length=300, null=True, verbose_name='Zip')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=300, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=300, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Rack name')),
                ('location', models.CharField(max_length=300, verbose_name='Rack Location')),
                ('active', models.BooleanField(default=True)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Rack',
                'verbose_name_plural': 'Warehouse Racks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseShelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Shelf name')),
                ('location', models.CharField(max_length=300, verbose_name='Shelf Location')),
                ('active', models.BooleanField(default=True)),
                ('warehouse_rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouserack')),
            ],
            options={
                'verbose_name': 'Warehouse Shelf',
                'verbose_name_plural': 'Warehouse Shelfs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_decimal', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('base_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('active', models.BooleanField(default=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Item Warehouse',
                'verbose_name_plural': 'Item Warehouses',
                'ordering': ['item_id'],
            },
        ),
    ]
