# Generated by Django 4.0.2 on 2022-11-08 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationlocation',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
